### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by Seongmun-Hong** [lincolnhard/openpose-darknet#2]
hello. I am a college student interested in machine learning. I want to try something you made. But I did not even start, I arrived at a difficult place. Could you tell me how to build your program?
I have installed both darknet and openpose. What commands can I use to build this program? I am waiting for your help.

**Comment by HongSungMoon** [comment]
Further work was done.
I set LD_LIBRARY_PATH as my issue below.
After that, I tried to compile with the following command.
g ++ -std = c ++ 11 main.cpp -o main $ (pkg-config --libs --cflags opencv)

The results are shown below.
/tmp/ccSviDZY.o: In function `main ':
main.cpp :(. text + 0x2b2a): undefined reference to `init_net '
main.cpp :(. text + 0x2d6c): undefined reference to `run_net '
collect2: error: ld returned 1 exit status

I am waiting for your help.
I want to run this great project.

**Comment by Seongmun-Hong** [comment]
After a little more checking, I went ahead. I checked and worked on my issue below.

First, I modified the darknet path in the .pro file.
Then imgcodecs error in the following below issue.
So I added LIBS + = -lopencv_imgcodecs.
However, the results is as follows.

g ++ -Wl, -O1 -Wl, -rpath, / home / hong / anaconda3 / lib -o openpose-darknet main.o run_darknet.o -L / home / lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -L / home / hong / anaconda3 / lib -lQt5Core -lpthread
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFIsTiled@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFGetField@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFNumberOfStrips@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFClose@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFOpen@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFSetField@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0 '
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0 '
collect2: error: ld returned 1 exit status
Makefile: 166: recipe for target 'openpose-darknet' failed
make: *** [openpose-darknet] Error 1

Do you have any clues to help me?

**Comment by Seongmun-Hong** [comment]
I did an extra job.
I have overcome the libtiff problem and have successfully compiled it.
But I have another problem in running the example.

./openpose-darknet person.jpg openpose.cfg openpose.weight

I tried to run the example above, but I get the result 'error while loading shared libraries: libdarknet.so: cannot open shared object file: No such file or directory'. 

So I added LD_LIBRARY_PATH as you suggested in the issue below (set to the folder where libdarknet.so exists)
Is that what I set up?
Do you have any additional work to do?

**Comment by Seongmun-Hong** [comment]
I keep on solving myself ...
I solved the problem by specifying in ld.so.conf the location of the .so files for darknet and cudnn. But the result is a sagmentation fault.
I do not know the cause. I was trying to solve the error one by one, but now I get an error that I can not figure out why. I am waiting for your help.

**Comment by lincolnhard** [comment]
I don't know where the seg fault happened, but i will start find out. Do you have any clues? Sorry for that.

**Comment by Seongmun-Hong** [comment]
Sorry. It was my mistake.

I succeeded in building and running your great project.I want to study this project a bit more. 
I have one additional question. Did you learn the weight file you used for your project? 
If that's true, did you just learn people? 
Can you tell the amount and time of learning data (in addition to your GPU)

Thank you very much for your reply. Thank you very much for opening your great

**Comment by lincolnhard** [comment]
Hi, I didn't retrain the model, just convert original caffe model to darknet format.

**Comment by Seongmun-Hong** [comment]
Thank you very much for your reply. I have studied a lot on your project. Thank you.
